### ISSUE TITLE
Version 1.x is completely different than 0.x versions

### ISSUE THREAD

**Issue by Cyclodex** [aleclarson/build-if-changed#8]
Hi, i just wanted to inform you that the package I used before was 0.x and i did not get any info / or migration guide or whatever that the 1.x release is completely different.

I just updated now and found out that everything is different.
Maybe the version should have been different, or at least any hint in the readme about prev packages versions.

Maybe this would help others as well.

Before I did use it to run a `npm ci` when the `package-lock.json` was changed.
So users only had to re-install npm packages if they really changed.
I think this doesn't work anymore with this build setup. Or do you have any tips how you would do that?

Cheers

**Comment by aleclarson** [comment]
See my response here: https://github.com/mweststrate/build-if-changed/issues/4#issuecomment-508443496

To make this difference more obvious, I'll update the README when I get a chance.
